services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facility_reg_infra
    volumes:
      # Mount your local Azure config and credentials
      - .azure:/home/azureuser/.azure:rw
      # Mount your project directory
      - .:/workspace
      # Mount SSH keys if you have them
      - .ssh:/home/azureuser/.ssh:ro
    env_file: .env
    working_dir: /workspace
    stdin_open: true
    tty: true
    # Keep container running
    command: tail -f /dev/null
    # Restart policy for development
    restart: unless-stopped

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
